### ISSUE TITLE
Setup.hs fails with Cabal-2.0.0.2

### ISSUE THREAD

**Issue by Mikolaj** [magthe/hsini#20]
It works fine with Cabal-1.24.2.0, but fails with newer cabals, that are official for 8.2.1 (https://downloads.haskell.org/~ghc/master/users-guide/8.2.1-notes.html#cabal). I guess the problem is due to a known and easily worked around API change, but I forgot the details:

```
~/r/hsini$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1
~/r/hsini$ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library 
~/r/hsini$ cabal clean
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )

dist/setup/setup.hs:33:35: error:
    • Couldn't match type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
                     with ‘[Char]’
      Expected type: FilePath
        Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
    • In the first argument of ‘(</>)’, namely ‘_eN’
      In the second argument of ‘(</>)’, namely ‘_eN </> _eN’
      In the expression: bldDir </> _eN </> _eN
   |
33 |                 _exe = bldDir </> _eN </> _eN
   |                                   ^^^

dist/setup/setup.hs:33:43: error:
    • Couldn't match type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
                     with ‘[Char]’
      Expected type: FilePath
        Actual type: Distribution.Types.UnqualComponentName.UnqualComponentName
    • In the second argument of ‘(</>)’, namely ‘_eN’
      In the second argument of ‘(</>)’, namely ‘_eN </> _eN’
      In the expression: bldDir </> _eN </> _eN
   |
33 |                 _exe = bldDir </> _eN </> _eN
   |                                           ^^^

dist/setup/setup.hs:35:41: error:
    • Couldn't match expected type ‘[Char]’
                  with actual type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
    • In the first argument of ‘(++)’, namely ‘_eN’
      In the second argument of ‘(++)’, namely ‘_eN ++ ":"’
      In the second argument of ‘($)’, namely ‘"** " ++ _eN ++ ":"’
   |
35 |                     putStrLn $ "** " ++ _eN ++ ":"
   |                                         ^^^

dist/setup/setup.hs:38:35: error:
    • Couldn't match expected type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
                  with actual type ‘[Char]’
    • In the expression: "tests"
      In the second argument of ‘elem’, namely ‘["tests"]’
      In the first argument of ‘when’, namely ‘(_eN `elem` ["tests"])’
   |
38 |                 when (_eN `elem` ["tests"]) _runTest
   |                                   ^^^^^^^
```

**Comment by Mikolaj** [comment]
Thank you!

**Comment by Mikolaj** [comment]
Ouch, this error is back in the version published on Hackage. :(

**Comment by Mikolaj** [comment]
E.g., here: https://ci.appveyor.com/project/Mikolaj/lambdahack-4hh0j

That's because the commit that fixes this was not included in the Hackage release.
